### ISSUE TITLE
How to access  RNA-Seq and Microarray Experiment Search 

### ISSUE THREAD

**Issue by zqfang** [mgijax/mousemine#16]
Hi MGI team,
      GXD has add RNA-seq data. Is there a way to get RNA-seq assay results? I search the whole API, but hardly find it. Thank you very much .

zqfang

**Comment by JoelRichardson** [comment]
Hi @zqfang , Unfortunately RNA-seq data are not available through MouseMine at this time. You can download expression data as tab delimited text from the main GXD web pages however. I hope that will meet your needs for now. Thank you for your interest. --Joel

**Comment by zqfang** [comment]
@JoelRichardson , thank you very much for your rely. I would like to do batch queries for a list a of genes and check whether they are expressed in a target tissue/organ or not.
